version: "3.7"

services:
  database:
    image: postgres
    container_name: queries_challenge
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=queries_challenge